### ISSUE TITLE
Access issues for Twitter API v2

### ISSUE THREAD

**Issue by swyxio** [algolia/we-rate-tweets#38]
hi! thanks for this!

just tried out implementing this https://swyxio-search.glitch.me/ and am getting this error:

```
APIError: You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve
    at /rbd/pnpm-volume/984a8525-7147-4eb1-b9bd-19ac773bed6f/node_modules/.registry.npmjs.org/passport-twitter/1.0.4/node_modules/passport-twitter/lib/strategy.js:138:23
    at passBackControl (/rbd/pnpm-volume/984a8525-7147-4eb1-b9bd-19ac773bed6f/node_modules/.registry.npmjs.org/oauth/0.9.15/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/rbd/pnpm-volume/984a8525-7147-4eb1-b9bd-19ac773bed6f/node_modules/.registry.npmjs.org/oauth/0.9.15/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:978:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

![image](https://user-images.githubusercontent.com/6764957/147411064-ac0ce8be-081b-46ea-b2c6-e42205cc4a1d.png)

i suspect you may not actually need the permissions you ask for here... wondering if you are able to trim the permissions down a bit?

i have applied for elevated access.

**Comment by Haroenv** [comment]
I saw you made it work now, do you mind doing a pull request with what you've changed, so it works better before we have the time to properly remake this demo?

**Comment by swyxio** [comment]
there's nothing to PR since i didnt fork.. but here https://glitch.com/edit/#!/swyxio-search
